config/routes.rb
Rails.application.routes.draw do
  
  #get 'home_pages/home'
  root 'home_pages#home'
  #get 'home_pages/help'
  get 'help'    => 'home_pages#help'
  #get 'home_pages/about'
  get 'about'   => 'home_pages#about'
  #get 'home_pages/contact'
  get 'all_entries'   => 'home_pages#all_entries'
  #get 'home_pages/contact'
  get 'contact' => 'home_pages#contact'
  #get 'users/new'
  get 'signup' =>'users#new'
  
  #get 'sessions/new'
  get 'signin' =>'sessions#new'
  post 'signin'=>'sessions#create'
  delete 'signout'=>'sessions#destroy'
  #get all resources users have index, show, new, create, edit, update,destroy
  resources :users
  resources :entries#,          only: [:create, :destroy]
  resources :comments,          only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end 
 resources :relationships, only: [:create, :destroy]
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home
    if signed_in?
  	  @entry=current_user.entries.build 
      @feed_items=current_user.feed.paginate(page: params[:page])
    else
       entries=Entry.all
      @feed_items=entries.paginate(page: params[:page])
    end
  end

  def help

  end

  def about

  end

  def contact

  end

  def all_entries    
      entries=Entry.all
      @feed_items=entries.paginate(page: params[:page])
  end
  
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/_anonymous.html.erb
<div class="row">
	<aside class="col-md-8">
		<div class="center jumbotron">
    		<%= render 'shared/feed'%>
		</div>  
	</aside>
	<!--set some style to the Entries-->
	<div class="col-md-4">	
	<!--check if user have any entries-->
	<b><font color="GREEN" style="font-family: Verdana; font-size:20pt">Sign up</font></b>
    <table width="100%" bgcolor="blue" border="0" cellpadding="0" cellspacing="20">
			<tbody><tr><td width="100%" align="center">
				<table style="font-family: Verdana; font-size:10pt" width="100%" border="0" cellpadding="0" cellspacing="0"> 
					<tbody><tr><td colspan="10" align="left">
					<%= form_for(:session, url: signin_path) do |f| %>
    				<!--add label eamil and text field email to form-->
      				<%= f.label :email %>
      				<%= f.text_field :email, class: 'form-control field_info'%>
      				<!--add label password and password field password to form-->
      				<%= f.label :password %>
      				<%= f.password_field :password, class: 'form-control field_info'%>
     				<!--add button sign in to form-->
      				<%= f.submit "Sign in", class: "btn btn-primary btn_commit" %>
    				<% end %>

    				<p>Need a account? <%= link_to "Sign up now!", signup_path %></p>
			</tbody></table>
			</td></tr>
		</tbody>

</table>
  </div>
</div>

app/views/home_pages/_login.html.erb
<div class="row">
    <aside class="col-md-4">
      <section class="user_info">
      <!--load file at app/view /shared/_user_info.html.erb-->
        <%= render 'shared/user_info' %>
      </section>
      <section class="status">
        <!--load the file in share folder-->
        <%=render 'shared/status'%>
      </section>
    </aside>
    <div class="col-md-8">

      <section class="entry_form">
      <!--load file at app/view /shared/_user_info.html.erb-->
        <%= render 'shared/entry_form' %>
      </section>
      <h3>New Feed</h3>
      <!--load file from app/view/shared/_feed.html.erb-->
      <div class="center jumbotron">
        <%= render 'shared/feed'%>
      </div>  
    </div>
  </div>

app/views/home_pages/about.html.erb
<% provide(:title, "About") %>

<h2>[Blog system requirements]</h2>
<h3>User</h3>
<p>- can sign-up </p>
<p>- can sign-in/sign-out </p>
<p>- can create a entry (display title, body, date)</p>
<p>- can make a comment on a entry (of owner and followed user) (display comment, name and date)</p>
<p>- can follow other users</p>
<p>- can see the latest entries which are posted by following users (with pagination)</p>

<h3>Everyone (including no sign-in user)</h3>
<p>- can read all posts and their comments (with pagination)</p>
<p>- cannot make a comment</p>

<h3>The model names you must use</h3>
<p>- User</p>
<p>- Entry</p>
<p>- Comment</p>
<p>- other model (if you need)</p>

<h3>Your system</h3>
<p>- is deployed on Heroku</p>

<h3>Your code</h3>
<p>- is uploaded on Github</p>

app/views/home_pages/all_entries.html.erb
<% provide(:title, "All User Entries") %>
 
      <center><h3>Entry Feed</h3></center>
      <!--load file from app/view/shared/_feed.html.erb-->
      <%= render 'shared/feed'%>     
 

app/views/home_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/home_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help
  section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
  Tutorial</em> book</a>.
</p>

app/views/home_pages/home.html.erb
<% provide(:title, "Home") %>
<% if signed_in? %>
  <%= render 'home_pages/login' %>
<% else %>
	<%= render 'home_pages/anonymous' %>
<%end%>