config/routes.rb
Rails.application.routes.draw do
  
  #get 'home_pages/home'
  root 'home_pages#home'
  #get 'home_pages/help'
  get 'help'    => 'home_pages#help'
  #get 'home_pages/about'
  get 'about'   => 'home_pages#about'
  #get 'home_pages/contact'
  get 'all_entries'   => 'home_pages#all_entries'
  #get 'home_pages/contact'
  get 'contact' => 'home_pages#contact'
  #get 'users/new'
  get 'signup' =>'users#new'
  
  #get 'sessions/new'
  get 'signin' =>'sessions#new'
  post 'signin'=>'sessions#create'
  delete 'signout'=>'sessions#destroy'
  #get all resources users have index, show, new, create, edit, update,destroy
  resources :users
  resources :entries#,          only: [:create, :destroy]
  resources :comments,          only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end 
 resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <div class="navbar navbar-fixed-bottom">
        <nav>
          <ul class="nav navbar-nav pull-right">
          	<%if signed_in?%>
          		<li><%= link_to "All Entry",   all_entries_path %></li>
	            <li><%= link_to "About",   about_path %></li>
	            <li><%= link_to "Contact",   contact_path %></li>    
	            <li><%= link_to "Help", help_path %></li>
	        <%else%>
	        	<li><%= link_to "About",   about_path %></li>
	            <li><%= link_to "Contact",   contact_path %></li>    
	            <li><%= link_to "Help", help_path %></li>
	        <%end%>    
          </ul>
        </nav>
      </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Connecting me", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
           
            <!--show this information when user signed in-->
            <% if signed_in? %>              
            <!--set style for dropdown  menu-->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b>
                </a>
                <!--add drop down items-->
                <ul class="dropdown-menu">

                  <li><%= link_to "Profile", current_user %></li>
                  <!--link to page update of user id follow the current id-->
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
              <!--else show this information when user not signed in-->
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--Looking for file name _shim.html.erb in app/views/layouts/-->
  <%= render 'layouts/shim' %>
</head>
<body>
	<!--Start Head of page-->
	<!--Looking for file name _header.html.erb in app/views/layouts/-->
	<%= render 'layouts/header' %>
    <!--End Head of page-->
    <div class="container">
      <!--use flash to show message in flash has-->
      <% flash.each do | message_type, message|%>
        <!--Alert message to let user know-->
        <div class="alert alert-<%= message_type%>"><%=message%></div>
      <% end%>
      <%= yield %>
      <!--Looking for file name _footer.html.erb in app/views/layouts/-->
      <%= render 'layouts/footer' %>
      <!--show debug if in development Enviroment-->
     
    </div>
</body>
</html>